baseURL: "https://giacomoanastasia.github.io/"
title: Giacomo Anastasia
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: CV
          url: cv.pdf
          weight: 2

params:
    description: "Giacomo Anastasia is a PhD student in Economics at Columbia University. His research focuses on public economics, labor economics, and industrial organization."
    author: Giacomo Anastasia
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Giacomo Anastasia
          subtitle: "I am a PhD student in Economics at Columbia University. My research focuses on public economics, labor economics, and industrial organization."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Tags
              url: tags/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:giacomo.anastasia@columbia.edu
        - name: Twitter
          url: https://x.com/GiAnastasia
        - name: LinkedIn
          url: https://www.linkedin.com/in/giacomo-anastasia-8266621a8/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=1ChXPRoAAAAJ
        - name: GitHub
          url: https://github.com/GiacomoAnastasia

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Giacomo Anastasia"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
